bundler_args: "--binstubs --without documentation"
script: "script/test_all && bin/rake --backtrace 2>&1"
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
