bundler_args: "--binstubs"
script: "script/test_all && bin/rake --trace 2>&1"
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
matrix:
  allow_failures:
    - rvm: rbx-18mode
    - rvm: rbx-19mode
    - rvm: jruby-18mode
    - rvm: jruby-19mode

