script: "script/test_all"
bundler_args: "--standalone --binstubs --without documentation"
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode
  - jruby-19mode
  - ree
  - rbx-2.2.1
  - rbx
  - 2.0.0
matrix:
  allow_failures:
    - rvm: rbx-2.2.1
    - rvm: rbx

