script: "script/test_all && bin/rake cucumber --trace 2>&1"
bundler_args: "--binstubs"
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode
  - jruby-19mode
  - ree
  - rbx-18mode
  - rbx-19mode
matrix:
  allow_failures:
    - rvm: jruby-19mode
